### PR TITLE
Mass update

### PR DESCRIPTION
**Pull request by HaydenAtFoxHaven**
Changes:
- New type `OrderedEffectCell` with `EffectOrder`
- Full documentation + doctests
- Operator passthrough
- Custom `Debug` impls
- `update_lambda` and `set_lambda`
- Update README with new examples for features
- Github Actions for CI testing
- No longer `no_std` due to requirement of `Vec` for multiple effect bindings

Note: There is a lot changed so the git diffs look like a mess

### CODE REVIEW

**Review by fprasx — COMMENTED** [review]
Thank you so much! One thing: could you add a note saying that effects are run in the order in which they are added?

**Comment by HaydenAtFoxHaven** [comment]
> Thank you so much! One thing: could you add a note saying that effects are run in the order in which they are added?

No problem! I have just committed it now.

**Comment by qrnch-jan** [comment]
Could an `as_ref()` (or similar name) be added to get an immutable reference to the inner data?

**Comment by fprasx** [comment]
Yes, that seems useful. @ScratchCat458 feel free to add it to the PR. Otherwise, I have no problem adding it in after this is merged.

EDIT: nevermind I see you added the previous thing

**Comment by fprasx** [comment]
Thank you so much @ScratchCat458!

**Pull request merged**
